---
ansible_python_interpreter: /usr/bin/python3
ansible_user: root
ansible_ssh_private_key_file: "{{ ssh_private_key_file }}"

remote_user: ubuntu
cache_time: 604800 # one week in seconds
ssh_public_key_file: ./ansible.pub
